// This file is automatically generated. Do not modify it manually.
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBLhsdvKyWe4YJKV0eRTIg6DrZiQTlmRIw",
  authDomain: "rcvvsm.firebaseapp.com",
  projectId: "rcvvsm",
  storageBucket: "rcvvsm.firebasestorage.app",
  messagingSenderId: "262481318704",
  appId: "1:262481318704:web:c6336b46c58dd0a342aef5",
  measurementId: "G-Z08B1L24TY",
  databaseURL: "https://rcvvsm-default-rtdb.firebaseio.com",
};
